@extends('web.layouts.principal')
@section('content')
    <contactenos-component></contactenos-component>
@endsection
@section('scripts')
    <script>
        $('#inicio').removeClass("active");
        $('#habitaciones').removeClass("active");
        $('#instalaciones').removeClass("active");
        $('#contactenos').addClass("active");
    </script>
@endsection
